workflows:
  ios-build:
    name: iOS Build
    environment:
      flutter: 3.32.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean Flutter build
        script: flutter clean

      - name: Get Flutter packages
        script: flutter pub get

      - name: Run pod install
        script: |
          cd ios
          pod install
          cd ..

      - name: Build iOS app
        script: flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/Runner.app

    publishing:
      email:
        recipients:
          - wdavidw26@gmail.com
