workflows:
  ios-build:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Build iOS app
        script: flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/Runner.app

    publishing:
      email:
        recipients:
          - wdavidw26@gmail.com
