name: front_scaffold_flutter_v2
description: "This is a base project in Flutter designed as a template for future developments. It contains essential configurations and packages to quickly start new projects."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1
  go_router: ^14.7.2
  animate_do: ^3.3.4
  intl: any
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  image_picker: ^1.1.2
  formz: ^0.8.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.1
  flutter_svg: ^2.0.17
  firebase_core: ^3.11.0
  firebase_messaging: ^15.2.2
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/loaders/
    - assets/icon/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: MontserratAlternates
      fonts:
        - asset: assets/fonts/montserrat_alternates/MontserratAlternates-Light.ttf
        - asset: assets/fonts/montserrat_alternates/MontserratAlternates-Regular.ttf
        - asset: assets/fonts/montserrat_alternates/MontserratAlternates-Medium.ttf
        - asset: assets/fonts/montserrat_alternates/MontserratAlternates-SemiBold.ttf
        - asset: assets/fonts/montserrat_alternates/MontserratAlternates-Bold.ttf