name: klero_app
description: "Todo app"
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.6.0

dependencies:
  animate_do: ^4.2.0
  cloud_firestore: ^5.6.7
  dio: ^5.8.0+1
  equatable: ^2.0.7
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  firebase_remote_config: ^5.4.3
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_local_notifications: ^19.2.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.1.0
  formz: ^0.8.0
  go_router: ^15.1.2
  google_fonts: ^6.2.1
  hydrated_bloc: ^10.0.0
  image_picker: ^1.1.2
  intl: any
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  versionarte: ^2.0.1

dev_dependencies:
  bloc_test: ^10.0.0
  change_app_package_name: ^1.5.0
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/loaders/
    - assets/icon/
    - assets/fonts/
    - assets/images/
    - assets/app-icon/
    - assets/images/create_task.png

  fonts:
    - family: MontserratAlternates
      fonts:
        - asset: assets/fonts/montserrat_alternates/MontserratAlternates-Light.ttf
        - asset: assets/fonts/montserrat_alternates/MontserratAlternates-Regular.ttf
        - asset: assets/fonts/montserrat_alternates/MontserratAlternates-Medium.ttf
        - asset: assets/fonts/montserrat_alternates/MontserratAlternates-SemiBold.ttf
        - asset: assets/fonts/montserrat_alternates/MontserratAlternates-Bold.ttf

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/app-icon/app-icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#D1C4E9"

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#512DA8"
  image: "assets/app-icon/native_splash_icon.png"

  android_12:
    color: "#ffffff"
    color_dark: "#512DA8"
    image: "assets/app-icon/native_splash_icon.png"
    # branding: "assets/app-icon/native_splash_icon.png"
