name: front_scaffold_flutter_v2
description: "This is a base project in Flutter designed as a template for
  future developments. It contains essential configurations and packages to
  quickly start new projects."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.6.0

dependencies:
  animate_do: ^3.3.4
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_dotenv: ^5.2.1
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  formz: ^0.8.0
  get_it: ^8.0.3
  go_router: ^14.7.2
  google_fonts: ^6.2.1
  hydrated_bloc: ^10.0.0
  image_picker: ^1.1.2
  intl: any
  introduction_screen: ^3.1.17
  path_provider: ^2.1.5
  shared_preferences: ^2.5.1

dev_dependencies:
  bloc_test: ^10.0.0
  change_app_package_name: ^1.4.0
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/loaders/
    - assets/icon/
    - assets/fonts/
    - assets/images/
    - assets/images/introduction/

  fonts:
    - family: MontserratAlternates
      fonts:
        - asset: assets/fonts/montserrat_alternates/MontserratAlternates-Light.ttf
        - asset: assets/fonts/montserrat_alternates/MontserratAlternates-Regular.ttf
        - asset: assets/fonts/montserrat_alternates/MontserratAlternates-Medium.ttf
        - asset: assets/fonts/montserrat_alternates/MontserratAlternates-SemiBold.ttf
        - asset: assets/fonts/montserrat_alternates/MontserratAlternates-Bold.ttf
